### PR TITLE
ISSUE-50: In React-Native v0.28 the Carousel no longer scrolls horizo…

### PR DESCRIPTION
**Pull request by sghiassy**
…ntally. This PR upgrades Carousel.js to work with RN v0.28

Credit goes to @dmccer. I just verified that the code change indeed resolves the problem and took the extra step of submitting a PR.

### CODE REVIEW

**Comment by sghiassy** [comment]
Thanks @nick for the quick merge!! Will you be able to `npm publish` soon?

**Comment by nick** [comment]
Yea I just did a few mins ago: https://www.npmjs.com/package/react-native-carousel

**Comment by sghiassy** [comment]
@nick - Wow. I'm impressed :)

**Comment by sghiassy** [comment]
Thx again!

**Pull request merged**
